language: java

services:
  - docker

jobs:
  include:
    - stage: test
      name: 'Testing application'
      services:
        - postgresql
      before_script:
        - psql -c 'create database devops;' -U postgres
      script:
        - make build/test
    - stage: package
      name: 'Packaging application'
      script:
        - make build/package
    - stage: docker
      name: 'Dockerize our app'
      script:
        - make build/docker
    - stage: deploy
      if: branch == master
      name: 'Deploy our app production'
      script:
        - make build/deploy/production
    - stage: deploy
      if: branch != master
      name: 'Deploy our app to staging'
      script:
        - make build/deploy/production