spring:
  datasource:
    url: "${DATABASE_URL:'jdbc:postgresql://localhost/devops'}"
    username: "${DATABASE_USERNAME:postgres}"
    password: "${DATABASE_PASSWORD:postgres}"
  jpa:
    hibernate:
      ddl-auto: validate